`.predict` is frequently used to make predictions for  a single datapoint or an entire dataframe

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
df = pd.read_csv('../Course Materials/Data/Diamonds Prices2022.csv')
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [6]:
X = sm.add_constant(df[['carat']])
y =df['price']

In [7]:
model_sm = sm.OLS(y, X).fit()
model_sm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.849
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                 3.041e+05
Date:                Sat, 13 Dec 2025   Prob (F-statistic):               0.00
Time:                        02:29:12   Log-Likelihood:            -4.7276e+05
No. Observations:               53943   AIC:                         9.455e+05
Df Residuals:                   53941   BIC:                         9.455e+05
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -2256.3950     13.055   -172.840      0.000   -2281.983   -2230.807
carat       7756.4362     14.066    551.423      0.000    7728.866    7784.006
==============================================================================
Omnibus:                    14027.005   Durbin-Watson:                   0.986
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           153060.389
Skew:                           0.939   Prob(JB):                         0.00
Kurtosis:                      11.036   Cond. No.                         3.65
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
model_sm.predict() # when we do not pass anything as an input the model predicts the price based on the training set

array([-472.41473085, -627.54345404, -472.41473085, ..., 3250.67462571,
       3250.67462571, 3173.11026412], shape=(53943,))

In [8]:
model_sm.predict([1, 1.5]) # 1 adds a constant (not starting from the origin) and 1.5 is the carat that we would like to predict the price of

array([9378.25919172])

In [ ]:
model_sm.predict([2])

ValueError: shapes (1,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [11]:
# the model is expecting 2 columns:  one for the constant and one for th feature, 
model_sm.predict([1,2])

array([13256.47727148])

In [14]:
# predict the entire dataframe
new_df = pd.DataFrame({'carat': [0,1,2,3,4,5]})
model_sm.predict(sm.add_constant(new_df))

0    -2256.395048
1     5500.041112
2    13256.477271
3    21012.913431
4    28769.349590
5    36525.785750
dtype: float64